### PR TITLE
Feature/refactoring

### PR DESCRIPTION
**Pull request by benedictleejh**
Summary of major refactored changes:

- Renamed modules to remove `hypedyn-` prefix (prefix remains in jar names)
- Moved each module's code into their own packages
- Update Scala to 2.12.3
- Update dependencies
- Change of log location (OS specific locations instead of a common location)
- Change of settings storage location (no longer using Java Preferences API)
- Serialisation moved from core to API
- Use scalafx-utils instead of EasyBind
- Use better-files to standardise file handling API

### CODE REVIEW

**Comment by lexaay** [comment]
Sorry for the slow response. Currently my build of the latest code doesn't run on my Mac, but I suspect its a setup issue (error is "Failed to launch JVM") as it does run from within IntelliJ. I'll try to approve the pull request soon, once I get the build working... :)

**Comment by lexaay** [comment]
Updated to jdk 1.8.0_151 and scala 2.12.3 but still not able to run.

**Comment by lexaay** [comment]
I have the same problem on Windows - runs fine from within IntelliJ, but I get the errors "Error invoking method." and "Failed to launch JVM" when running from the build version.

**Comment by benedictleejh** [comment]
Ok, the crash should be fixed now. Apparently the new IO API library that I use has a different behaviour when listing files from a non-existent folder than the base Java API; it crashes instead of just returning an empty list. That's fixed now.

**Comment by lexaay** [comment]
Thanks, its working on both platforms now. I'll do some more extensive testing then if everything seems ok I'll approve the pull request. :)

**Pull request merged**
